name: barber
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  iconly: ^1.0.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^8.0.3
  injectable: ^2.5.0
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  flutter_svg: ^2.0.9
  build_runner: ^2.5.4
  vector_graphics: ^1.1.19
  go_router: ^16.0.0
  logger: ^2.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  flutter_gen_runner: ^5.10.0
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-VariableFont_wght.ttf

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
